# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 'node-cli-action'
description: 'node js cli word app'
inputs:
  source:
    description: 'Basic CLI application with node js.'
    required: true
  destination:
    description: 'The destination filename will be'
    required: false
    default: 'screenshot.png'
outputs:
  path:
    description: 'The filesystem path'
runs:
  using: 'node12'
  main: 'app/index.js'
branding:
  icon: 'camera'
  color: 'black'
